on:
  workflow_call:
    # inputs:
    #   tag:
    #     required: true
    #     type: string
    # secrets:
    #   GHCR_TOKEN_RW:
    #     required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          registry-url: "https://npm.pkg.github.com"
      - run: jq '.name = "@${{ github.repository }}"' package.json > tmp && mv tmp package.json
      - run: jq '.version = "${{ GITHUB_SHA }}"' package.json > tmp && mv tmp package.json
      - run: npm i
      - run: npm run build
      - run: |
          echo "Lets check it >>>"
          ls -alh .
          cat package.json
      - run: npm publish --tag ${GITHUB_REF_NAME}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GHCR_TOKEN_RW }}
