on:
  workflow_call:
    inputs:
      registry:
        required: true
        type: string
      tag:
        required: true
        type: string
      NODE_AUTH_TOKEN:
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          registry-url: ${{ inputs.registry }}
      - run: npm ci
      - run: npm run build
      - run: npm publish --tag ${{ inputs.tag }}
        env:
          NODE_AUTH_TOKEN: ${{ inputs.NODE_AUTH_TOKEN }}
