on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          registry-url: "https://npm.pkg.github.com"
      - run: |
          NAME='@${{ github.repository }}'
          VERSION=$(cat package.json | jq -r .version)-$(git rev-parse HEAD | cut -c 1-8)
          echo $(jq ".name = \"${NAME}\"" package.json) > package.json
          echo $(jq ".version = \"${VERSION}\"" package.json) > package.json
          cat package.json
      - run: npm ci
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GHCR_TOKEN_RW }}
