name: "Publish test coverage"

on:
  push:
    branches: [master]

jobs:
  coverage:
    name: Sending test coverage to Code Climate 📊
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - run: npm ci
      - uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_TEST_REPORTER_ID }}
        with:
          coverageCommand: npm run test:coverage
          coverageLocations: ${{github.workspace}}/coverage/lcov.info:lcov
          debug: true
